language: c
sudo: false

matrix:
    include:
        - os: linux
          env:
              - MATRIX_EVAL="CC=gcc-7"
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7

before_install:
    - eval "${MATRIX_EVAL}"

script:
    - make
notifications:
    email: false
