language: c
dist: xenial
sudo: required
services:
    - docker
before_install:
    - docker-compose -f ci/docker-compose.yml build
script:
    - make
    - docker-compose -f ci/docker-compose.yml run test
notifications:
    email: false
