language: c
sudo: false

matrix:
    include:
        - os: linux
          env:
              - CC=gcc-7
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-7

script:
    - make
notifications:
    email: false
