language: c
dist: xenial
sudo: required
services:
    - docker
before_install:
    - docker-compose build -f ci/docker-compose.yml
script:
    - make
    - docker-compose run test -f ci/docker-compose.yml
notifications:
    email: false
